### PR TITLE
Reworking TC-type configs

### PR DESCRIPTION
**Pull request by ArturSztuc**
PR explained in: https://github.com/DUNE-DAQ/trigger/pull/351

### CODE REVIEW

**Review by aeoranday — COMMENTED** [review]
I noticed that `CustomTCMakerConf` still uses the integer type design instead of the new string one here. Is this an oversight?

https://github.com/DUNE-DAQ/appmodel/blob/develop/schema/appmodel/trigger.schema.xml#L130

**Comment by ArturSztuc** [comment]
@aeoranday 
> I noticed that `CustomTCMakerConf` still uses the integer type design instead of the new string one here. Is this an oversight?
> 
> https://github.com/DUNE-DAQ/appmodel/blob/develop/schema/appmodel/trigger.schema.xml#L130

A little bit of an oversight: `CustomTCMaker` wasn't being used for anything in v5 tests, and it ended up being severaly out-of date, thanks for pointing this out.
There's more than just the TC-types to resolve here:
1. TC-types as you noticed
2. Replacing `trigger_intervals` with `trigger_rate_hz`
3. Removal of `clock_frequency_hz`
4. Complete rework of `CustomTCMaker` in a similar way to what was done to `RandomTCMaker` in https://github.com/DUNE-DAQ/trigger/pull/350

I'm happy to do this, but probably in a separate PR. For now `CustomTCMaker` is so out of date that probably shouldn't be used...

In fact, perhaps we should completely wipe out `CustomTCMaker` from existance. `RandomTCMaker` has configurable TC-type and TC-window output, and we can have multiple `RandomTCMaker`s running concurrently... making `CustomTCMaker` a bit redundant.

**Comment by aeoranday** [comment]
The argument for removing `CustomTCMaker` is sensible, and I agree that it would be out-of-scope for this PR. Though, I imagine it will remain a low priority and end up taking a while before removing.

**Review by aeoranday — APPROVED** [review]
LGTM.

**Comment by ArturSztuc** [comment]
Thank you Alex. I was going to go through trigger issues page and resolve as many as possible over the next ~2 weeks, and I see that `CustomTCMaker` features in a few of them - I'll work on that next, so it won't be forgotten :)

**Pull request merged**
