### PR TITLE
JCF: Issue #135: add a session argument to create_config_plot to allo…

### PR DESCRIPTION
**Pull request by jcfreeman2**
…w it to disambiguate when there are multiple sessions in a database

To learn how to use it, read the updated documentation currently on the feature branch at
https://github.com/DUNE-DAQ/appmodel/tree/johnfreeman/issue135_multiple_sessions?tab=readme-ov-file#creating-a-diagram-of-your-configuration

### CODE REVIEW

**Comment by bieryAtFnal** [comment]
I ran some tests, and here are some notes:

- `create_config_plot -f config/daqsystemtest/example-configs.data.xml -s local-1x1-config -r local-1x1-config` produces the expected result (a plot of the 1x1 config)
- `create_config_plot -f config/daqsystemtest/example-configs.data.xml -s local-1x1-config -r local-2x3-config` reports no error and produces a plot of the 1x1 config.  This was a little unexpected, since I expected some sort of warning or error.
- `create_config_plot -f config/daqsystemtest/example-configs.data.xml -s local-2x3-config -r local-1x1-config` results in a crash (that is a little hard to notice among the other output from the app).  Here is the message from the console:
    - `create_config_plot: /home/nfs/biery/dunedaq/08OctFDDevBleedingEdgeTest3/sourcecode/appmodel/src/GraphBuilder.cpp:415: void appmodel::GraphBuilder::find_objects_and_connections(const ConfigObject&): Assertion `!m_objects_for_graph.contains(object.UID())' failed.`
- `create_config_plot -f config/daqsystemtest/example-configs.data.xml -s local-2x3-config -r local-2x3-config` produces the expected result (a plot of the 2x3 config)

Was I doing something wrong in the 2nd and 3rd tests?

**Comment by jcfreeman2** [comment]
For 2 at least, the problem is that the algorithm searched _all_ objects in the database and needs to be narrowed to only search objects associated with the session. I'll make the needed fixes for (2) and (3) tomorrow morning; in particular (3) should be a cleaner, more informative error than an assertion fault.

**Comment by jcfreeman2** [comment]
OK, I've updated the code. To get into details, now what happens is the code builds an internal, preliminary graph with the requested session as the root node, and checks that the actual requested root node is in the preliminary graph before proceeding as before.

**Comment by bieryAtFnal** [comment]
Thanks.  I've confirmed that the commands that I listed earlier now either work or give a clear error message.

Unrelated to all of that, the ability to skip the "-s" argument when there is only one session in the database is nice.  Could there be support for a scenario where the "-r" argument is optional, namely when users *do* specify the "-s" argument and they would like the "seesion" root object to be plotted?

**Comment by jcfreeman2** [comment]
Added support for defaulting the root object to the session name; updated documentation [here](https://github.com/DUNE-DAQ/appmodel/tree/johnfreeman/issue135_multiple_sessions?tab=readme-ov-file#creating-a-diagram-of-your-configuration)

**Review by bieryAtFnal — APPROVED** [review]
Looks great to me.
Thanks, John.

**Pull request merged**
